// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelloWorld.Migrations
{
    [DbContext(typeof(KcgContext))]
    partial class KcgContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kcg.Models.TOPMenu", b =>
                {
                    b.Property<Guid>("TOPMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Orders")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TOPMenuId");

                    b.ToTable("TOPMenu");

                    b.HasData(
                        new
                        {
                            TOPMenuId = new Guid("83d37ac1-d155-453f-83fb-8b838bb5e727"),
                            Icon = "Icon1",
                            Name = "網站導覽",
                            Orders = 1,
                            Url = "a1"
                        },
                        new
                        {
                            TOPMenuId = new Guid("55adf662-0e1a-4689-b4ed-e5a83e744746"),
                            Icon = "Icon2",
                            Name = "回首頁",
                            Orders = 2,
                            Url = "a2"
                        },
                        new
                        {
                            TOPMenuId = new Guid("839fe886-5a13-4f72-af42-01edc363436c"),
                            Icon = "Icon3",
                            Name = "English",
                            Orders = 3,
                            Url = "a3"
                        },
                        new
                        {
                            TOPMenuId = new Guid("85c418f5-15ea-496b-be60-f741e088ea2b"),
                            Icon = "Icon4",
                            Name = "雙語詞彙",
                            Orders = 4,
                            Url = "a4"
                        },
                        new
                        {
                            TOPMenuId = new Guid("5c20aef8-a54c-4bb9-a10b-818ea58e4325"),
                            Icon = "Icon5",
                            Name = "市長信箱",
                            Orders = 5,
                            Url = "a5"
                        },
                        new
                        {
                            TOPMenuId = new Guid("c3fb8eed-f7b5-43ff-9531-8d5058f19280"),
                            Icon = "Icon6",
                            Name = "洽公導覽",
                            Orders = 6,
                            Url = "a6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
